INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (1, 'Életciklus', 1724234495281, 'Az alkalmazás elindult', 'Rendszer') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (2, 'Principal létrehozva', 1724234495532, 'admin | Adminisztrátor', 'Ismeretlen végrehajtó') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (3, 'Principal módosítva', 1724234685023, 'Isti | Adminisztrátor', 'admin (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (4, 'Principal létrehozva', 1724234714282, 'Pultos1 | Terminál', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (5, 'Számla létrehozva', 1724234763662, '1: Horváth István - isti@simonyi.bme.hu', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (6, 'Számla létrehozva', 1724234797299, '2: Példa Petra - petra@gmail.com', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (7, 'Számla létrehozva', 1724234818483, '3: Example Elemér', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (8, 'Termék létrehozva', 1724234839256, 'Sör: 100000 db, 400 JMF - Aktív', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (9, 'Termék létrehozva', 1724234851282, 'Somersby Apple: 100000 db, 500 JMF - Aktív', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (10, 'Termék létrehozva', 1724234865852, 'Unicum: 0 db, 999 JMF - Aktív', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (11, 'Termék létrehozva', 1724234879666, 'Unicum Barista: 100000 db, 999 JMF - Inaktív', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (12, 'Kártya hozzárendelve', 1724234909218, '1: Horváth István - isti@simonyi.bme.hu', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (13, 'Kártya hozzárendelve', 1724234927778, '2: Példa Petra - petra@gmail.com', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (14, 'Feltöltés', 1724234939192, '1: Horváth István - isti@simonyi.bme.hu | 1000 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (15, 'Feltöltés', 1724234943816, '2: Példa Petra - petra@gmail.com | 1000 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (16, 'Feltöltés', 1724234949424, '1: Horváth István - isti@simonyi.bme.hu | 1000 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (17, 'Átutalás', 1724234962255, '2: Példa Petra - petra@gmail.com -> 1: Horváth István - isti@simonyi.bme.hu | 1000 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (18, 'Fizetés', 1724234990553, '1: Horváth István - isti@simonyi.bme.hu | 1000 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (19, 'Számla szerkesztve', 1724235003771, '2: Példa Petra - petra@gmail.com', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (20, 'Kártya hozzárendelve', 1724235003776, '1: Horváth István - isti@simonyi.bme.hu', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (21, 'Számla szerkesztve', 1724235011752, '1: Horváth István - isti@simonyi.bme.hu', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (22, 'Kártya hozzárendelve', 1724235011755, '2: Példa Petra - petra@gmail.com', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (23, 'Kártya hozzárendelve', 1724235016498, '1: Horváth István - isti@simonyi.bme.hu', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (24, 'Fizetés', 1724235048256, '1: Horváth István - isti@simonyi.bme.hu | 1000 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (25, 'Fizetés', 1724235048273, '1: Horváth István - isti@simonyi.bme.hu | 400 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (26, 'Rendelés létrehozva', 1724235048243, 'Rendelésazonosító: 1 - Számlaazonosító: 1', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (27, 'Termék eladva', 1724235048281, 'Rendelésazonosító: 1 - Számlaazonosító: 1 | Mennyiség: 1, Fizetve: 200, Termék: Ropi', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (28, 'Termék eladva', 1724235048264, 'Rendelésazonosító: 1 - Számlaazonosító: 1 | Mennyiség: 2, Fizetve: 1000, Termék: Somersby Apple', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (29, 'Termék eladva', 1724235048275, 'Rendelésazonosító: 1 - Számlaazonosító: 1 | Mennyiség: 1, Fizetve: 400, Termék: Sör', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (30, 'Fizetés', 1724235048279, '1: Horváth István - isti@simonyi.bme.hu | 200 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (31, 'Életciklus', 1724235211633, 'Az alkalmazás leállt', 'Rendszer') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (32, 'Principal létrehozva', 1724234495532, 'admin | Adminisztrátor', 'Ismeretlen végrehajtó') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (33, 'Principal létrehozva', 1724234714282, 'Pultos1 | Terminál', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (34, 'Életciklus', 1724235214161, 'Az alkalmazás elindult', 'Rendszer') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (35, 'Principal létrehozva', 1724235214248, 'admin | Adminisztrátor', 'Ismeretlen végrehajtó') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (36, 'Életciklus', 1724235234677, 'Az alkalmazás leállt', 'Rendszer') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (37, 'Principal létrehozva', 1724235214248, 'admin | Adminisztrátor', 'Ismeretlen végrehajtó') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (38, 'Életciklus', 1724235236319, 'Az alkalmazás elindult', 'Rendszer') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (39, 'Utalvány Létrehozva', 1724235309302, 'Számlaazonosító: 2, Termékazonosító: 3, Darabszám: 100', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (40, 'Kártya hozzárendelve', 1724235667785, '1: Horváth István - isti@simonyi.bme.hu', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (41, 'Számla szerkesztve', 1724235667775, '2: Példa Petra - petra@gmail.com', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (42, 'Életciklus', 1724235775645, 'Az alkalmazás leállt', 'Rendszer') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (43, 'Életciklus', 1724235777370, 'Az alkalmazás elindult', 'Rendszer') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (44, 'Kártya hozzárendelve', 1724235815232, '2: Példa Petra - petra@gmail.com', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (45, 'Utalvány Létrehozva', 1724235873438, 'Számlaazonosító: 1, Termékazonosító: 1, Darabszám: 2', 'Isti (admin)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (46, 'Utalvány beváltva', 1724235886179, 'Rendelésazonosító: 15 - Számlaazonosító: 1', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (47, 'Utalvány módosítva', 1724235886171, 'Számlaazonosító: 1, Termékazonosító: 1, Darabszám: 1', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (48, 'Rendelés létrehozva', 1724235886161, 'Rendelésazonosító: 15 - Számlaazonosító: 1', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (49, 'Rendelés létrehozva', 1724235934318, 'Rendelésazonosító: 18 - Számlaazonosító: 1', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (50, 'Termék eladva', 1724235934324, 'Rendelésazonosító: 18 - Számlaazonosító: 1 | Mennyiség: 1, Fizetve: 400, Termék: Sör', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (51, 'Feltöltés', 1724235952657, '2: Példa Petra - petra@gmail.com | 5000 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (52, 'Feltöltés', 1724235957881, '1: Horváth István - isti@simonyi.bme.hu | 5000 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
INSERT INTO events (id, event, timestamp, message, performed_by) VALUES (53, 'Fizetés', 1724235972338, '2: Példa Petra - petra@gmail.com | 1500 JMF', 'Pultos1 (terminal)') ON CONFLICT DO NOTHING;
